"""city extra fields

Revision ID: 1e4e60b5b5a9
Revises: 9672e1ec42f7
Create Date: 2023-06-20 06:07:44.496040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4e60b5b5a9'
down_revision = '9672e1ec42f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owm_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('owm_id')

    # ### end Alembic commands ###
